name: patealo
description: Si no lo sabes, no lo uses

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  provider: ^6.0.1
  path_provider: ^2.0.0
  cached_network_image: ^3.1.0+1
  http: ^0.13.4
  image_picker: ^0.8.4+4
  flutter_tts: ^3.2.2
  google_fonts: ^2.1.0
  flutter_speech: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
